version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"

  fog_node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fog_node
    environment:
      - MQTT_BROKER_ADDRESS=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=dadosfog
    depends_on:
      - mosquitto

  edge_node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edge_node
    environment:
      - MQTT_BROKER_ADDRESS=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=dadosedge
    depends_on:
      - mosquitto

  carro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carro
    environment:
      - MQTT_BROKER_ADDRESS=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=dadoscarros
      - FLASK_APP=computador_bordo.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - mosquitto

  publicador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: publicador
    environment:
      - MQTT_BROKER_ADDRESS=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=dadoscarros
    depends_on:
      - mosquitto
